version: "3.3"

networks:
  messagingservice:

services:
  messageservice:
    image: ninjafx/messageservice:latest
    networks:
      - messagingservice
    ports:
      - "8002:80"
    environment:
      - DOTNET_ENVIRONMENT=docker
    depends_on:
      - rabbitmq
      - mongo
      
  rabbitmq:
    image: rabbitmq:3.8.14-management
    networks:
      - messagingservice
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

  mongo:
    image: "mongo"
    networks:
      - messagingservice
    ports:
      - '27017-27019:27017-27019'
